.PHONEY = all

THREADS := 3 # Speed is largely limited by decompression rate
INSTANCES := 4 # Total threads = THREADS * INSTANCES

all:
	python3 install/scripts/identify_adapters.py input/*.yaml --threads $(THREADS) | parallel -j $(INSTANCES) -u
	python3 install/scripts/classify_adapters.py output/*.txt | tee output.tsv
